# .forgejo/workflows/go-build-check.yaml

name: Go Build Error Check

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  build-and-check-go:
    runs-on: codeberg-tiny

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build all Go modules
        run: |
          set -e
          echo "Searching for and building all Go modules..."
          for dir in $(find . -name "go.mod" -exec dirname {} \;); do
            if [ "$dir" != "." ]; then
              echo "--- Building module in $dir ---"
              (cd "$dir" && go mod tidy && go build ./...)
            fi
          done
          echo "All Go modules built successfully."
