# .forgejo/workflows/nix-build-check.yaml

name: Nix Build Check

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  nix-build:
    runs-on: codeberg-tiny

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: https://github.com/nixbuild/nix-quick-install-action@v1

      - name: Build with Nix
        run: |
          echo "Building all packages with Nix..."
          nix build .
          echo "Nix build completed successfully."
