name: tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  nix-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix-shell --packages alejandra --run "alejandra --check ."
